import type { CatalogCategory, CatalogItem, CategoryId } from "./types";

export const CATEGORY_COLORS: Record<CategoryId, string> = {
  patient: "#dff3df",
  disease: "#f8ddd3",
  symptom: "#ffffff",
  test: "#ffffff",
  treatment: "#fff0bd",
  neutral: "#ffffff",
};

export const CATEGORIES: CatalogCategory[] = [
  {
    id: "patient",
    label: "患者情報",
    color: CATEGORY_COLORS.patient,
    subcategories: ["基本情報", "既往歴", "生活背景", "家族・社会背景", "ADL"],
  },
  {
    id: "disease",
    label: "疾患",
    color: CATEGORY_COLORS.disease,
    subcategories: [
      "循環器",
      "呼吸器",
      "消化器",
      "血液・造血器",
      "脳・神経",
      "腎・泌尿器",
      "内分泌・代謝",
      "救急・全身管理",
      "免疫・アレルギー",
      "感染症",
      "運動器・整形",
      "皮膚",
      "眼",
      "耳鼻咽喉",
      "女性生殖器・母性",
      "精神",
      "その他",
    ],
  },
  {
    id: "symptom",
    label: "症状・所見",
    color: CATEGORY_COLORS.symptom,
    subcategories: [
      "全身",
      "呼吸器",
      "循環器",
      "消化器",
      "脳・神経",
      "腎・泌尿器",
      "血液・出血",
      "内分泌・代謝",
      "運動器・疼痛",
      "皮膚・炎症所見",
      "感覚器",
      "排泄",
      "精神・心理",
      "その他",
    ],
  },
  {
    id: "test",
    label: "検査",
    color: CATEGORY_COLORS.test,
    subcategories: [
      "バイタルサイン",
      "血算",
      "生化学検査",
      "凝固検査",
      "免疫・血清検査",
      "尿検査",
      "便検査",
      "微生物検査",
      "画像検査",
      "生理検査",
      "病理・細胞検査",
      "その他",
    ],
  },
  {
    id: "treatment",
    label: "治療・薬剤",
    color: CATEGORY_COLORS.treatment,
    subcategories: [
      "抗感染症薬",
      "解熱・鎮痛薬",
      "循環器系薬",
      "その他の薬剤",
      "輸液",
      "輸血",
      "手術",
      "処置",
      "放射線治療",
      "食事療法",
      "リハビリテーション",
      "その他",
    ],
  },
  {
    id: "neutral",
    label: "自由入力",
    color: CATEGORY_COLORS.neutral,
    subcategories: ["通常ボックス", "見出し", "メモ"],
  },
];

function items(
  category: CategoryId,
  subcategory: string,
  labels: string[],
): CatalogItem[] {
  return labels.map((label) => ({
    id: `builtin:${category}:${subcategory}:${label}`,
    label,
    category,
    subcategory,
  }));
}

export const CATALOG_ITEMS: CatalogItem[] = [
  ...items("disease", "呼吸器", [
    "COPD",
    "肺炎",
    "高二酸化炭素血症",
    "呼吸不全",
    "肺水腫",
    "気管支喘息",
    "気胸",
    "肺高血圧症",
    "肺血栓塞栓症",
  ]),
  ...items("disease", "循環器", [
    "心不全",
    "閉塞性動脈硬化症（ASO）",
    "静脈血栓塞栓症（VTE）",
    "洞不全症候群（SSS）",
    "心筋梗塞",
    "大動脈解離",
    "高血圧症",
    "不整脈",
    "弁膜症",
    "心タンポナーデ",
    "心嚢液貯留",
  ]),
  ...items("disease", "内分泌・代謝", [
    "糖尿病",
    "下垂体機能低下症",
  ]),
  {
    id: "builtin:disease:内分泌・代謝:hhs",
    label: "高浸透圧高血糖状態（HHS）",
    category: "disease",
    subcategory: "内分泌・代謝",
    aliases: ["非ケトン性高浸透圧昏睡"],
  },
  ...items("disease", "腎・泌尿器", [
    "前立腺肥大症",
    "尿路感染症",
    "腎盂腎炎",
    "電解質異常",
    "ネフローゼ症候群",
    "急性腎障害（AKI）",
    "横紋筋融解症",
  ]),
  {
    id: "builtin:disease:腎・泌尿器:ckd",
    label: "慢性腎臓病（CKD）",
    category: "disease",
    subcategory: "腎・泌尿器",
    aliases: ["慢性腎不全"],
  },
  ...items("disease", "脳・神経", [
    "硬膜下血腫",
    "脳梗塞",
    "脳浮腫",
    "脳ヘルニア",
    "くも膜下出血",
    "正常圧水頭症",
    "脳出血",
  ]),
  ...items("disease", "皮膚", [
    "褥瘡",
    "スキンテア",
    "失禁関連皮膚炎（IAD）",
    "蜂窩織炎",
  ]),
  ...items("disease", "救急・全身管理", [
    "ショック",
    "敗血症",
    "感染症",
    "静脈炎",
    "低栄養",
    "リフィーディング症候群",
    "廃用症候群",
  ]),
  ...items("disease", "消化器", [
    "膵炎",
    "肝不全",
    "肝障害",
    "肝硬変",
    "ダンピング症候群",
  ]),
  ...items("disease", "運動器・整形", [
    "大腿骨頸部骨折",
    "圧迫骨折",
    "骨軟化症",
  ]),
  ...items("disease", "精神", ["認知症"]),

  ...items("symptom", "全身", [
    "発熱",
    "倦怠感",
    "食欲不振",
    "脱水",
    "熱感",
  ]),
  ...items("symptom", "呼吸器", [
    "咳嗽",
    "喀痰",
    "呼吸困難",
    "頻呼吸",
    "チアノーゼ",
    "SpO₂低下",
  ]),
  ...items("symptom", "循環器", [
    "胸痛",
    "血圧低下",
    "高血圧",
    "頸静脈怒張",
    "浮腫",
    "意識消失",
  ]),
  ...items("symptom", "消化器", ["腹痛", "悪心", "嘔吐", "腹水"]),
  ...items("symptom", "脳・神経", [
    "頭痛",
    "昏睡",
    "偏視",
    "麻痺",
    "羽ばたき振戦",
    "意識レベル低下",
    "しびれ",
  ]),
  ...items("symptom", "運動器・疼痛", ["背部痛", "疼痛"]),
  ...items("symptom", "皮膚・炎症所見", ["腫脹", "紅斑", "熱感"]),

  ...items("test", "血算", ["WBC", "好中球"]),
  ...items("test", "免疫・血清検査", ["CRP", "赤沈"]),
  ...items("test", "生化学検査", [
    "LDH",
    "CK",
    "AST",
    "ALT",
    "ビリルビン",
    "Alb",
    "BUN",
    "トロポニンT",
    "Na",
    "K",
    "Ca",
    "Mg",
    "P（無機リン／IP）",
    "Cl",
  ]),
  ...items("test", "凝固検査", ["Dダイマー", "FDP"]),
  ...items("test", "生理検査", ["SpO₂", "PaO₂", "PaCO₂"]),

  ...items("treatment", "抗感染症薬", ["抗菌薬", "抗真菌薬"]),
  ...items("treatment", "解熱・鎮痛薬", ["解熱薬", "鎮痛薬"]),
  ...items("treatment", "循環器系薬", [
    "Ca拮抗薬",
    "硝酸薬",
    "β遮断薬",
    "利尿薬",
    "昇圧薬",
    "降圧薬",
  ]),
  ...items("treatment", "その他の薬剤", [
    "ステロイド薬",
    "アンモニア産生・吸収抑制薬",
  ]),
];

export const SYSTEMS = [
  "未分類",
  "循環器",
  "呼吸器",
  "消化器",
  "血液・造血器",
  "脳・神経",
  "腎・泌尿器",
  "内分泌・代謝",
  "救急・全身管理",
  "免疫・アレルギー",
  "感染症",
  "運動器・整形",
  "皮膚",
  "眼・耳鼻咽喉",
  "女性生殖器・母性",
  "小児",
  "精神",
  "その他",
];

export function getCategory(id: CategoryId) {
  return CATEGORIES.find((category) => category.id === id) ?? CATEGORIES[5];
}
